version: '3.8'

services:
  db:
    build:
      context: ./db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  api:
      build:
        context: ./api
      ports:
        - "3000:3000"
      depends_on:
        - db
      environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

volumes:
  db_data:      

      